### ISSUE TITLE
Missing bccName

### ISSUE THREAD

**Issue by adrianbj** [horst-n/WireMailSmtp#6]
Hi @horst-n - just wondering if this is intentional or an oversight?

**Comment by horst-n** [comment]
Hi @adrianbj, this is intentional, as there is neither an emailadress nor a sender name is sent with **blind** carbone copies. At least I haven't seen this anywhere. If this is wrong, please can you then sent me an example?

**Comment by adrianbj** [comment]
Swiftmailer allows you to set the bccName: http://swiftmailer.org/docs/messages.html#setting-bcc-recipients

**Comment by horst-n** [comment]
Ok, but I cannot understand for what it is good. After you have set it, it got deleted respectively it is not used for anything. It is neither transmitted with the mails to the origin recipients or the CC recipients, nor is it transmitted to the BCC recipient. This behaves with the address and the name, otherwise it wouldn't be a blind copy.
If you can tell me that / how it makes sense, I will add it. :)

**Comment by adrianbj** [comment]
I am actually seeing it transmitted in some cases:
![screen shot 2016-07-19 at 1 21 12 pm](https://cloud.githubusercontent.com/assets/871211/16965300/63fdc42c-4db4-11e6-8d0e-953d696b6c0f.png)

Also, lots of other libraries/services are using it:
https://sendgrid.com/docs/API_Reference/Web_API/mail.html
https://github.com/Remiii/remiii-mandrill-mailer-bundle/blob/master/src/SwiftMailer/MandrillTransport.php#L214
https://github.com/AccordGroup/MandrillSwiftMailer/blob/master/SwiftMailer/MandrillTransport.php#L259

Honestly I almost never use Bcc at all - in fact I don't think I have ever used it when sending emails from a web script.

But I think more than anything it maybe should be included for consistency with other services, but I won't hassle you anymore if you don't think it is necessary :)

**Comment by horst-n** [comment]
Ok. If some clients transmit it, and people are knowing this from other libs, I will add it. :)
