### ISSUE TITLE
replyable queue

### ISSUE THREAD

**Issue by krisj** [horst-n/WireMailSmtp#7]
feature request/idea. A bit of a head scratch. I am experiencing issues with clients changing their email account passwords and as a result breaking the module sending.

One thing is to log the sending/connection errors but the messages are long gone too. So, how about an email queue implementation where all messages would queue up if they cannot be sent for some reason and then upon fixing the issue whatever it might be the admin could resend the queued emails again?

There is lots to do I guess but I thought I'd throw it out there.

**Comment by teppokoivula** [comment]
We discussed a similar concept with a co-worker back when I released WireMailSwiftMailer. At the time I was planning to bolt such feature directly on to my module, but he made a very good point: why not a separate module that intercepts outgoing email and thus isn't dependent on a specific WireMail implementation?

I've had so much other stuff on my plate since then that this was put on a back burner, but I do still think that it would be a welcome addition. In fact we've got a tool like that built-in into our in-house CMS system, and it has definitely proven to be worth it's weight (?) in gold over the past years. 

Being able to stop processing the queue for a while in case of a maintenance break or resend messages after a failure is awesome :)

**Comment by horst-n** [comment]
I'm with @teppokoivula here. It is definetly better to have this as standalone module, dealing / hooking into the wiremail base class. Don't know how much work it needs to build such a feature, but want to mention that we now have a nearly stable WireQueue implementation ready for use: https://github.com/horst-n/WireQueue
